spring:
  application:
    name: collector

collector:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    send-timeout: ${COLLECTOR_KAFKA_SEND_TIMEOUT:10s}
    producer:
      acks: all
      enable-idempotence: true
      compression-type: snappy
      linger-ms: 5
      batch-size: 32768
      max-in-flight-requests-per-connection: 5
    topics:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1
