CREATE TABLE scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_scenarios_hub_id_name UNIQUE (hub_id, name)
);

CREATE TABLE sensors (
    id VARCHAR(255) PRIMARY KEY,
    hub_id VARCHAR(255) NOT NULL
);

CREATE TABLE conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    operation VARCHAR(64) NOT NULL,
    "value" INTEGER
);

CREATE TABLE actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    "value" INTEGER
);

CREATE TABLE scenario_conditions (
    scenario_id BIGINT NOT NULL,
    sensor_id VARCHAR(255) NOT NULL,
    condition_id BIGINT NOT NULL,
    CONSTRAINT pk_scenario_conditions PRIMARY KEY (scenario_id, sensor_id, condition_id),
    CONSTRAINT fk_scenario_conditions_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_scenario_conditions_sensor FOREIGN KEY (sensor_id) REFERENCES sensors(id) ON DELETE CASCADE,
    CONSTRAINT fk_scenario_conditions_condition FOREIGN KEY (condition_id) REFERENCES conditions(id) ON DELETE CASCADE
);

CREATE TABLE scenario_actions (
    scenario_id BIGINT NOT NULL,
    sensor_id VARCHAR(255) NOT NULL,
    action_id BIGINT NOT NULL,
    CONSTRAINT pk_scenario_actions PRIMARY KEY (scenario_id, sensor_id, action_id),
    CONSTRAINT fk_scenario_actions_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_scenario_actions_sensor FOREIGN KEY (sensor_id) REFERENCES sensors(id) ON DELETE CASCADE,
    CONSTRAINT fk_scenario_actions_action FOREIGN KEY (action_id) REFERENCES actions(id) ON DELETE CASCADE
);

CREATE TABLE action_dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id VARCHAR(255) NOT NULL,
    scenario_name VARCHAR(255) NOT NULL,
    snapshot_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    snapshot_version BIGINT NOT NULL,
    sensor_id VARCHAR(255) NOT NULL,
    action_type VARCHAR(64) NOT NULL,
    action_value INTEGER,
    CONSTRAINT uk_action_dispatches_snapshot_action
        UNIQUE (hub_id, scenario_name, snapshot_version, sensor_id, action_type, action_value)
);

CREATE INDEX idx_sensors_hub_id
    ON sensors (hub_id);

CREATE INDEX idx_scenario_conditions_sensor_id
    ON scenario_conditions (sensor_id);

CREATE INDEX idx_scenario_actions_sensor_id
    ON scenario_actions (sensor_id);
